// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYPqw6rRR1whIqyGW6bnJTWdLQIopFBjg',
    appId: '1:63324663954:web:311a123b06adbf9a48364b',
    messagingSenderId: '63324663954',
    projectId: 'digital-design-ec1f3',
    authDomain: 'digital-design-ec1f3.firebaseapp.com',
    databaseURL: 'https://digital-design-ec1f3-default-rtdb.firebaseio.com',
    storageBucket: 'digital-design-ec1f3.firebasestorage.app',
    measurementId: 'G-C0NHH5L6CL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATYzlBR_vwIKIDlrOSEPJOYyOgU29hxEE',
    appId: '1:63324663954:android:513c23416731935248364b',
    messagingSenderId: '63324663954',
    projectId: 'digital-design-ec1f3',
    databaseURL: 'https://digital-design-ec1f3-default-rtdb.firebaseio.com',
    storageBucket: 'digital-design-ec1f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNa5kwqT0hNH_CdB5XuSs73fOil4N-sDs',
    appId: '1:63324663954:ios:abf50b0dd2381ff648364b',
    messagingSenderId: '63324663954',
    projectId: 'digital-design-ec1f3',
    databaseURL: 'https://digital-design-ec1f3-default-rtdb.firebaseio.com',
    storageBucket: 'digital-design-ec1f3.firebasestorage.app',
    iosBundleId: 'com.example.clinicCompanion',
  );
}
